In [3]:
import numpy as np
import pandas as pd

In [4]:
A = [20,1,3,30]
print(A)

[20, 1, 3, 30]


In [5]:
s = pd.Series(A)
print(s)

0    20
1     1
2     3
3    30
dtype: int64


In [6]:
print(type(s))

<class 'pandas.core.series.Series'>


In [7]:
tup = (20,1,3,30)
s = pd.Series(A)
print(s)

0    20
1     1
2     3
3    30
dtype: int64


In [8]:
arr = np.arange(1,10)
sr = pd.Series(arr)
print(sr)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


In [9]:
D = {"Name":["Somu","Anil","Rohan","Gini"]}
print(D)

{'Name': ['Somu', 'Anil', 'Rohan', 'Gini']}


In [10]:
sr = pd.Series(D)
print(sr)

Name    [Somu, Anil, Rohan, Gini]
dtype: object


In [18]:
g = sr["Name"][2]
print(g)

Rohan


In [20]:
arr = 
print(arr)
# np.ndim(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [22]:
sr = pd.Series(arr)
print(sr)

ValueError: Data must be 1-dimensional, got ndarray of shape (3, 3) instead